try {
    {
        let x=10;
    }
    console.log(x);
}
catch(err){
    console.log(err);
}
finally{
    console.log("Hii");
}